Algoritmo "Conversor"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Gustavo Guanabara
// Descrição   : Estudante
// Autor(a)    : Fernando Cruz
// Data atual  : 02/08/2020
Var
// Seção de Declarações das variáveis 
   angulo, s: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva ("Digite um valor do Angulo: ")
   Leia (angulo)
   s <- Sen(GraupRad(angulo))
   Escreva("O Seno de ", angulo, " é: ", s)

Fimalgoritmo