Algoritmo "MeuNome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Gustavo Guanabara
// Descrição   : Estudante
// Autor(a)    : Fernando Cruz
// Data atual  : 02/08/2020
Var
// Seção de Declarações das variáveis 
   Nome: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva ("Digite seu nome: ")
   Leia (Nome)
   Escreval ("Muito prazer ", Nome)

Fimalgoritmo