Algoritmo "Operadores_Logicos"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Gustavo Guanabara
// Descrição   : Estudante
// Autor(a)    : Fernando Cruz
// Data atual  : 02/08/2020
Var
// Seção de Declarações das variáveis 
   A, B, C: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   A <- 2
   B <- 3
   C <- 5
   Escreva ((A=B) e (A<C))

Fimalgoritmo